#!/usr/bin/expect --
spawn /usr/bin/mysql_secure_installation

expect "Enter current password for root (enter for none):"
send "\r"

expect "Set root password?"
send "\r"

expect "New password:"
send "vagrant\r"

expect "Re-enter new password:"
send "vagrant\r"

expect "Remove anonymous users?"
send "\r"

expect "Disallow root login remotely?"
send "\r"

expect "Remove test database and access to it?"
send "\r"

expect "Reload privilege tables now?"
send "\r"
